export const SWIPE_ASK = 'SWIPE_ASK'
export const SWIPE_ASK_PENDING = `${SWIPE_ASK}_PENDING`
export const SWIPE_ASK_FULFILLED = `${SWIPE_ASK}_FULFILLED`
export const SWIPE_ASK_REJECTED = `${SWIPE_ASK}_REJECTED`

export const NEXT_SWIPE_ASK = 'NEXT_SWIPE_ASK'
export const NEXT_SWIPE_ASK_PENDING = `${NEXT_SWIPE_ASK}_PENDING`
export const NEXT_SWIPE_ASK_FULFILLED = `${NEXT_SWIPE_ASK}_FULFILLED`
export const NEXT_SWIPE_ASK_REJECTED = `${NEXT_SWIPE_ASK}_REJECTED`

export const CREATE_ASK = 'CREATE_ASK'
export const CREATE_ASK_PENDING = `${CREATE_ASK}_PENDING`
export const CREATE_ASK_FULFILLED = `${CREATE_ASK}_FULFILLED`
export const CREATE_ASK_REJECTED = `${CREATE_ASK}_REJECTED`