{
    home: 'Ask anyone, anything',

    facebookForm_hello: 'Bonjour',
    facebookForm_username: 'Nom d\'utilisateur',
    facebookForm_register: 'S\'ISNCRIRE',
    facebookForm_act1: 'Erreur',
    facebookForm_act2: 'Veuillez ressayer',
    facebookForm_act3: 'Ce nom d\'utilisateur est déjà utilisé',

    contact_text:'Certains de vos contacts sont peut-être déjà sur spitch',
    contact_text2:'Retrouvez les dès maintenant.',
    contact_btn:'Retrouver via Facebook',
    contact_nxt:'Passer',

    listFeed_question:'Posez votre question',

    spitchFeed_text1:'a repondu à',
    spitchFeed_act1:'Supprimer du file d\'actualité',
    spitchFeed_act2:'Signaler',
    spitchFeed_act3:'Annuler',
    spitchFeed_report1:'Merci',
    spitchFeed_report2:'Votre signalement a bien été pris en compte.',

    createAsk_title:'Posez votre question',
    createAsk_text1:'Posez votre question à la communauté',
    createAsk_text2:'Ajoutez des # pour toucher un',
    createAsk_text3:'maximum d\'utilisateurs.',
    createAsk_btn:'ENVOYER AU SPITCHER',
    createAsk_act1:'Bravo',
    createAsk_act2:'Question envoyé !',
    createAsk_act3:'Erreur',
    createAsk_act4:'Veuillez recommencer',
    createAsk_act5:'Désolé',
    createAsk_act6:'Votre question semble un peu courte',

    profileHeader_follow1:'Abonnée',
    profileHeader_follow2:'S\'abonner',
    profileHeader_data1:'Videos',
    profileHeader_data2:'Followers',
    profileHeader_data3:'Follows',
    profileHeader_btn1:'Modifier le profil',
    profileHeader_tab1:'Mes spitchs',
    profileHeader_tab2:'Mes questions',
    profileHeader_text1:'Ajoutez une description',

    listSpitchProfile_act1:'Supprimer la video',
    listSpitchProfile_act2:'Annuler',
    listSpitchProfile_act3:'Suppression',
    listSpitchProfile_act4:'Etes-vous sur de vouloir supprimer cette video ?',
    listSpitchProfile_act5:'Oui',
    listSpitchProfile_act6:'Annuler',

    listAskProfile_text1:'réponse',

    listFacebook_title:'Amis de facebook',
    listFacebook_text1:'Error...',
    listFacebook_text2:'Nouveau',
    listFacebook_btn1:'Follow',
    listFacebook_btn2:'Follow All',

    listRelation_title:'Abonné',
    listRelation_text1:'Error...',
    listRelation_text2:'Aucun utilisateur trouvé',
    listRelation_text3:'Rechercher',
    listRelation_btn1:'Follow',

    userUpdate_title:'Modifier mon profil',
    userUpdate_text1:'Changer de photo',
    userUpdate_text2:'Nom d\'utilisateur',
    userUpdate_text3:'Décrivez-vous',
    userUpdate_btn1:'ENREGISTRER',
    userUpdate_act1:'Enregistré',
    userUpdate_act2:'Ce nom d\'utilisateur est déjà utilisé',

    swipeAsk_text1:'Par',
    swipeAsk_text2:'Voir les',
    swipeAsk_text3:'réponses',
    swipeAsk_text4:'Aucune réponse',

    recorder_act1:'Confirmation',
    recorder_act2:'Voulez-vous supprimer le dernier enregistrement ?',
    recorder_act3:'Annuler',

    replay_act1:'Merci :)',
    replay_act1:'Votre spitch a bien été envoyé !',
    replay_btn:'ENVOYER',

    utilsDate_dt1:'Hier',
    utilsDate_dt2:'Demain',
    utilsDate_dt3:'jours',
    utilsDate_dt4:'Semaine dernière',
    utilsDate_dt5:'Next week',
    utilsDate_dt6:'semaines',
    utilsDate_dt7:'Mois dernier',
    utilsDate_dt8:'Next month',
    utilsDate_dt9:'mois',
    utilsDate_dt10:'L\'année dernière',
    utilsDate_dt11:'Next year',
    utilsDate_dt12:'années',
    utilsDate_dt13:'maintenant',

    userSettings_title:'Parametre du compte',
    userSettings_text1:'Mon compte',
    userSettings_text2:'Email',
    userSettings_text3:'Mot de passe',
    userSettings_text4:'Notification',
    userSettings_text5:'Notification',
    userSettings_text6:'Déconnexion',

    notification_text1:'Aucune notification',
    notification_text2:'vous suit',
    notification_text3:'a posé une nouvelle question : ',
    notification_text4:'vous a posé une question :',
    notification_text5:'a repondu à :',
    notification_text6:'a repondu à votre question :',
}