export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_REQUESTED = 'AUTH_REQUESTED'

export const AUTH = 'AUTH'
export const AUTH_PENDING = `${AUTH}_PENDING`
export const AUTH_FULFILLED = `${AUTH}_FULFILLED`
export const AUTH_REJECTED = `${AUTH}_REJECTED`

export const AUTH_USER_NOT_EXISTS = 'AUTH_USER_NOT_EXISTS'
export const AUTH_USER_NOT_EXISTS_PENDING = `${AUTH_USER_NOT_EXISTS}_PENDING`
export const AUTH_USER_NOT_EXISTS_FULFILLED = `${AUTH_USER_NOT_EXISTS}_FULFILLED`
export const AUTH_USER_NOT_EXISTS_REJECTED = `${AUTH_USER_NOT_EXISTS}_REJECTED`

export const AUTH_REGISTER_FACEBOOK = 'AUTH_REGISTER_FACEBOOK'
export const AUTH_REGISTER_FACEBOOK_PENDING = `${AUTH_REGISTER_FACEBOOK}_PENDING`
export const AUTH_REGISTER_FACEBOOK_FULFILLED = `${AUTH_REGISTER_FACEBOOK}_FULFILLED`
export const AUTH_REGISTER_FACEBOOK_REJECTED = `${AUTH_REGISTER_FACEBOOK}_REJECTED`