
// get notification
export const LIST_NOTIFICATION = 'LIST_NOTIFICATION'
export const LIST_NOTIFICATION_PENDING = `${LIST_NOTIFICATION}_PENDING`
export const LIST_NOTIFICATION_FULFILLED = `${LIST_NOTIFICATION}_FULFILLED`
export const LIST_NOTIFICATION_REJECTED = `${LIST_NOTIFICATION}_REJECTED`

export const COUNT_NOTIFICATION = 'COUNT_NOTIFICATION'
export const COUNT_NOTIFICATION_PENDING = `${COUNT_NOTIFICATION}_PENDING`
export const COUNT_NOTIFICATION_FULFILLED = `${COUNT_NOTIFICATION}_FULFILLED`
export const COUNT_NOTIFICATION_REJECTED = `${COUNT_NOTIFICATION}_REJECTED`

export const RESET_COUNT_NOTIFICATION = "RESET_COUNT_NOTIFICATION"

export const REFRESH_NOTIFICATION = 'REFRESH_NOTIFICATION'
export const REFRESH_NOTIFICATION_PENDING = `${REFRESH_NOTIFICATION}_PENDING`
export const REFRESH_NOTIFICATION_FULFILLED = `${REFRESH_NOTIFICATION}_FULFILLED`
export const REFRESH_NOTIFICATION_REJECTED = `${REFRESH_NOTIFICATION}_REJECTED`


export const NEXT_NOTIFICATION = 'NEXT_NOTIFICATION'
export const NEXT_NOTIFICATION_PENDING = `${NEXT_NOTIFICATION}_PENDING`
export const NEXT_NOTIFICATION_FULFILLED = `${NEXT_NOTIFICATION}_FULFILLED`
export const NEXT_NOTIFICATION_REJECTED = `${NEXT_NOTIFICATION}_REJECTED`