
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED'

export const RETREIVE_USER = 'RETREIVE_USER'
export const RETREIVE_USER_PENDING = `${RETREIVE_USER}_PENDING`
export const RETREIVE_USER_FULFILLED = `${RETREIVE_USER}_FULFILLED`
export const RETREIVE_USER_REJECTED = `${RETREIVE_USER}_REJECTED`

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_PENDING = `${UPDATE_USER}_PENDING`
export const UPDATE_USER_FULFILLED = `${UPDATE_USER}_FULFILLED`
export const UPDATE_USER_REJECTED = `${UPDATE_USER}_REJECTED`

export const RETREIVE_USER_DATAS = 'RETREIVE_USER_DATAS'
export const RETREIVE_USER_DATAS_PENDING = `${RETREIVE_USER_DATAS}_PENDING`
export const RETREIVE_USER_DATAS_FULFILLED = `${RETREIVE_USER_DATAS}_FULFILLED`
export const RETREIVE_USER_DATAS_REJECTED = `${RETREIVE_USER_DATAS}_REJECTED`

export const LIST_USER_SPITCH = 'LIST_USER_SPITCH'
export const LIST_USER_SPITCH_PENDING = `${LIST_USER_SPITCH}_PENDING`
export const LIST_USER_SPITCH_FULFILLED = `${LIST_USER_SPITCH}_FULFILLED`
export const LIST_USER_SPITCH_REJECTED = `${LIST_USER_SPITCH}_REJECTED`

export const REMOVE_LIST_USER_SPITCH = 'REMOVE_LIST_USER_SPITCH'

export const NEXT_LIST_USER_SPITCH = 'NEXT_LIST_USER_SPITCH'
export const NEXT_LIST_USER_SPITCH_PENDING = `${NEXT_LIST_USER_SPITCH}_PENDING`
export const NEXT_LIST_USER_SPITCH_FULFILLED = `${NEXT_LIST_USER_SPITCH}_FULFILLED`
export const NEXT_LIST_USER_SPITCH_REJECTED = `${NEXT_LIST_USER_SPITCH}_REJECTED`

export const LIST_USER_ASK = 'LIST_USER_ASK'
export const LIST_USER_ASK_PENDING = `${LIST_USER_ASK}_PENDING`
export const LIST_USER_ASK_FULFILLED = `${LIST_USER_ASK}_FULFILLED`
export const LIST_USER_ASK_REJECTED = `${LIST_USER_ASK}_REJECTED`

export const NEXT_LIST_USER_ASK = 'NEXT_LIST_USER_ASK'
export const NEXT_LIST_USER_ASK_PENDING = `${NEXT_LIST_USER_ASK}_PENDING`
export const NEXT_LIST_USER_ASK_FULFILLED = `${NEXT_LIST_USER_ASK}_FULFILLED`
export const NEXT_LIST_USER_ASK_REJECTED = `${NEXT_LIST_USER_ASK}_REJECTED`