export const RETREIVE_VISIT = 'RETREIVE_VISIT'
export const RETREIVE_VISIT_PENDING = `${RETREIVE_VISIT}_PENDING`
export const RETREIVE_VISIT_FULFILLED = `${RETREIVE_VISIT}_FULFILLED`
export const RETREIVE_VISIT_REJECTED = `${RETREIVE_VISIT}_REJECTED`

export const RETREIVE_VISIT_DATAS = 'RETREIVE_VISIT_DATAS'
export const RETREIVE_VISIT_DATAS_PENDING = `${RETREIVE_VISIT_DATAS}_PENDING`
export const RETREIVE_VISIT_DATAS_FULFILLED = `${RETREIVE_VISIT_DATAS}_FULFILLED`
export const RETREIVE_VISIT_DATAS_REJECTED = `${RETREIVE_VISIT_DATAS}_REJECTED`

export const LIST_VISIT_SPITCH = 'LIST_VISIT_SPITCH'
export const LIST_VISIT_SPITCH_PENDING = `${LIST_VISIT_SPITCH}_PENDING`
export const LIST_VISIT_SPITCH_FULFILLED = `${LIST_VISIT_SPITCH}_FULFILLED`
export const LIST_VISIT_SPITCH_REJECTED = `${LIST_VISIT_SPITCH}_REJECTED`

export const NEXT_LIST_VISIT_SPITCH = 'NEXT_LIST_VISIT_SPITCH'
export const NEXT_LIST_VISIT_SPITCH_PENDING = `${NEXT_LIST_VISIT_SPITCH}_PENDING`
export const NEXT_LIST_VISIT_SPITCH_FULFILLED = `${NEXT_LIST_VISIT_SPITCH}_FULFILLED`
export const NEXT_LIST_VISIT_SPITCH_REJECTED = `${NEXT_LIST_VISIT_SPITCH}_REJECTED`

export const LIST_VISIT_ASK = 'LIST_VISIT_ASK'
export const LIST_VISIT_ASK_PENDING = `${LIST_VISIT_ASK}_PENDING`
export const LIST_VISIT_ASK_FULFILLED = `${LIST_VISIT_ASK}_FULFILLED`
export const LIST_VISIT_ASK_REJECTED = `${LIST_VISIT_ASK}_REJECTED`

export const NEXT_LIST_VISIT_ASK = 'NEXT_LIST_VISIT_ASK'
export const NEXT_LIST_VISIT_ASK_PENDING = `${NEXT_LIST_VISIT_ASK}_PENDING`
export const NEXT_LIST_VISIT_ASK_FULFILLED = `${NEXT_LIST_VISIT_ASK}_FULFILLED`
export const NEXT_LIST_VISIT_ASK_REJECTED = `${NEXT_LIST_VISIT_ASK}_REJECTED`

export const UNFOLLOW_VISIT = 'UNFOLLOW_VISIT'