export const LIST_FEED = 'LIST_FEED'
export const LIST_FEED_PENDING = `${LIST_FEED}_PENDING`
export const LIST_FEED_FULFILLED = `${LIST_FEED}_FULFILLED`
export const LIST_FEED_REJECTED = `${LIST_FEED}_REJECTED`

export const REFRESH_FEED = 'REFRESH_FEED'
export const REFRESH_FEED_PENDING = `${REFRESH_FEED}_PENDING`
export const REFRESH_FEED_FULFILLED = `${REFRESH_FEED}_FULFILLED`
export const REFRESH_FEED_REJECTED = `${REFRESH_FEED}_REJECTED`

export const NEXT_FEED = 'NEXT_FEED'
export const NEXT_FEED_PENDING = `${NEXT_FEED}_PENDING`
export const NEXT_FEED_FULFILLED = `${NEXT_FEED}_FULFILLED`
export const NEXT_FEED_REJECTED = `${NEXT_FEED}_REJECTED`

export const LIKE_FEED = 'LIKE_FEED'
export const DISLIKE_FEED = 'DISLIKE_FEED'

export const DELETE_FEED = 'DELETE_FEED'
export const DELETE_FEED_PENDING = `${DELETE_FEED}_PENDING`
export const DELETE_FEED_FULFILLED = `${DELETE_FEED}_FULFILLED`
export const DELETE_FEED_REJECTED = `${DELETE_FEED}_REJECTED`
