export const INIT_NEW_SPITH = 'INIT_NEW_SPITH'
export const ADD_CLIP_NEW_SPITCH = 'ADD_CLIP_NEW_SPITCH'
export const REMOVE_CLIP_NEW_SPITCH = 'REMOVE_CLIP_NEW_SPITCH'
export const MERGE_CLIP_NEW_SPITCH = 'MERGE_CLIP_NEW_SPITCH'
export const RESET_MERGE_CLIP_NEW_SPITCH = 'RESET_MERGE_CLIP_NEW_SPITCH'
export const RESET_NEW_SPITCH = 'RESET_NEW_SPITCH'

export const UPLOAD_SPITCH = 'UPLOAD_SPITCH'
export const UPLOAD_SPITCH_PENDING = `${UPLOAD_SPITCH}_PENDING`
export const UPLOAD_SPITCH_FULFILLED = `${UPLOAD_SPITCH}_FULFILLED`
export const UPLOAD_SPITCH_REJECTED = `${UPLOAD_SPITCH}_REJECTED` 

export const LIKE_SPITCH = 'LIKE_SPITCH'
export const LIKE_SPITCH_PENDING = `${LIKE_SPITCH}_PENDING`
export const LIKE_SPITCH_FULFILLED = `${LIKE_SPITCH}_FULFILLED`
export const LIKE_SPITCH_REJECTED = `${LIKE_SPITCH}_REJECTED` 

export const RETRIEVE_SPITCH = 'RETRIEVE_SPITCH'
export const RETRIEVE_SPITCH_PENDING = `${RETRIEVE_SPITCH}_PENDING`
export const RETRIEVE_SPITCH_FULFILLED = `${RETRIEVE_SPITCH}_FULFILLED`
export const RETRIEVE_SPITCH_REJECTED = `${RETRIEVE_SPITCH}_REJECTED` 

export const RESET_VIDEOS = 'RESET_VIDEOS'

export const LIST_SPITCH_ASK = 'LIST_SPITCH_ASK'
export const LIST_SPITCH_ASK_PENDING = `${LIST_SPITCH_ASK}_PENDING`
export const LIST_SPITCH_ASK_FULFILLED = `${LIST_SPITCH_ASK}_FULFILLED`
export const LIST_SPITCH_ASK_REJECTED = `${LIST_SPITCH_ASK}_REJECTED` 

export const NEXT_LIST_SPITCH_ASK = 'NEXT_LIST_SPITCH_ASK'
export const NEXT_LIST_SPITCH_ASK_PENDING = `${NEXT_LIST_SPITCH_ASK}_PENDING`
export const NEXT_LIST_SPITCH_ASK_FULFILLED = `${NEXT_LIST_SPITCH_ASK}_FULFILLED`
export const NEXT_LIST_SPITCH_ASK_REJECTED = `${NEXT_LIST_SPITCH_ASK}_REJECTED` 

export const REPORT_SPITCH = 'REPORT_SPITCH'
export const REPORT_SPITCH_PENDING = `${REPORT_SPITCH}_PENDING`
export const REPORT_SPITCH_FULFILLED = `${REPORT_SPITCH}_FULFILLED`
export const REPORT_SPITCH_REJECTED = `${REPORT_SPITCH}_REJECTED` 

export const DELETE_SPITCH = 'DELETE_SPITCH'
export const DELETE_SPITCH_PENDING = `${DELETE_SPITCH}_PENDING`
export const DELETE_SPITCH_FULFILLED = `${DELETE_SPITCH}_FULFILLED`
export const DELETE_SPITCH_REJECTED = `${DELETE_SPITCH}_REJECTED` 
