
export const LIST_FACEBOOK_FRIEND = 'LIST_FACEBOOK_FRIEND'
export const LIST_FACEBOOK_FRIEND_PENDING = `${LIST_FACEBOOK_FRIEND}_PENDING`
export const LIST_FACEBOOK_FRIEND_FULFILLED = `${LIST_FACEBOOK_FRIEND}_FULFILLED`
export const LIST_FACEBOOK_FRIEND_REJECTED = `${LIST_FACEBOOK_FRIEND}_REJECTED`

export const FOLLOW_USER = 'FOLLOW_USER'
export const FOLLOW_USER_PENDING = `${FOLLOW_USER}_PENDING`
export const FOLLOW_USER_FULFILLED = `${FOLLOW_USER}_FULFILLED`
export const FOLLOW_USER_REJECTED = `${FOLLOW_USER}_REJECTED`

export const UNFOLLOW_USER = 'UNFOLLOW_USER'
export const UNFOLLOW_USER_PENDING = `${UNFOLLOW_USER}_PENDING`
export const UNFOLLOW_USER_FULFILLED = `${UNFOLLOW_USER}_FULFILLED`
export const UNFOLLOW_USER_REJECTED = `${UNFOLLOW_USER}_REJECTED`

export const FOLLOW_ALL_USER = 'FOLLOW_ALL_USER'
export const FOLLOW_ALL_USER_PENDING = `${FOLLOW_ALL_USER}_PENDING`
export const FOLLOW_ALL_USER_FULFILLED = `${FOLLOW_ALL_USER}_FULFILLED`
export const FOLLOW_ALL_USER_REJECTED = `${FOLLOW_ALL_USER}_REJECTED`

export const ACTIVE_FACEBOOK_FRIEND = 'ACTIVE_FACEBOOK_FRIEND'
export const UNACTIVE_FACEBOOK_FRIEND = 'UNACTIVE_FACEBOOK_FRIEND'

export const ACTIVE_FOLLOW_USER = 'ACTIVE_FOLLOW_USER'
export const UNACTIVE_FOLLOW_USER = 'UNACTIVE_FOLLOW_USER'

export const LIST_RELATION = 'LIST_RELATION'
export const LIST_RELATION_PENDING = `${LIST_RELATION}_PENDING`
export const LIST_RELATION_FULFILLED = `${LIST_RELATION}_FULFILLED`
export const LIST_RELATION_REJECTED = `${LIST_RELATION}_REJECTED`